---
driver:
  name: vagrant
  forward_agent: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  # - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[hello-chef::default]
      - recipe[hello-chef::git]
      - recipe[hello-chef::zsh]
      - recipe[hello-chef::ruby]
      - recipe[hello-chef::vim]
      - recipe[hello-chef::mysql]
      - recipe[hello-chef::linux_programming]
    attributes:
      home_dir: "/home/vagrant"
      user: 'vagrant'
      group: 'vagrant'
      ruby:
        version: '2.2.0'
